Added resnest-50 model
openvinotoolkit/open_model_zoo pull request #1485
Opened 2020-08-31 09:35 UTC by Anna-Mironova

2020-08-31 10:01 UTC, eaidova commented
Jenkins please retry a build

2020-08-31 10:23 UTC, eaidova commented
Jenkins please retry a build

2020-08-31 10:52 UTC, eaidova approved these changes

2020-08-31 11:12 UTC, eizamaliev requested changes
Please, add model to models.lst for classification demo.

2020-08-31 12:25 UTC, IRDonch requested changes

2020-08-31 12:25 UTC, IRDonch commented on models/public/resnest-50/resnest-50.md
> +Channel order is `BGR`
```suggestion
Channel order is `BGR`.
```

2020-08-31 12:25 UTC, IRDonch commented on models/public/index.md
> +| ResNeSt 50                  | PyTorch\*                          | [resnest-50](./resnest-50/resnest-50.md) | 81.11%/95.36% | 10.8148 |  27.4493|
I think it should go before the ResNet models (since S comes before T).

2020-08-31 13:01 UTC, IRDonch approved these changes

2020-09-01 16:45 UTC, IRDonch commented
@Anna-Mironova There's now a merge conflict; please rebase.

2020-09-02 10:11 UTC, eizamaliev approved these changes

2020-09-02 11:27 UTC, merged