gmcnn-places2-tf is modified for BGR->BGR processing.
openvinotoolkit/open_model_zoo pull request #1499
Opened 2020-09-02 08:39 UTC by fzhar

Accuracy checker is updated correspondingly.

2020-09-02 09:02 UTC, eaidova approved these changes

2020-09-02 11:29 UTC, IRDonch commented
What you have looks good, but aren't you going to update `model.yml` to use the newly re-frozen model?

2020-09-06 21:14 UTC, vladimir-dudnik commented
Jenkins please retry a build

2020-09-06 21:16 UTC, vladimir-dudnik requested changes
please pay attention to @IRDonch comment on updating model.yml (if needed, or confirm that update is not required)

2020-09-07 10:16 UTC, vladimir-dudnik approved these changes

2020-09-07 10:22 UTC, vladimir-dudnik requested changes

2020-09-07 10:22 UTC, vladimir-dudnik commented on models/public/gmcnn-places2-tf/model.yml
>      source: https://download.01.org/opencv/public_models/022020/gmcnn/frozen_model.pb
seems yo need to specify new path to updated model, 092020, is not it?

2020-09-07 13:58 UTC, vladimir-dudnik commented
Jenkins please retry a build

2020-09-07 14:12 UTC, vladimir-dudnik commented
Jenkins please retry a build

2020-09-07 14:24 UTC, vladimir-dudnik commented
Jenkins ok to test

2020-09-08 07:59 UTC, vladimir-dudnik commented
Jenkins please retry a build

2020-09-08 09:47 UTC, fzhar commented
Jenkins please retry a build

2020-09-08 11:20 UTC, eaidova commented
Jenkins please retry a build

2020-09-09 14:16 UTC, vladimir-dudnik approved these changes

2020-09-09 16:19 UTC, merged