Add YOLO v4 model
openvinotoolkit/open_model_zoo pull request #1628
Opened 2020-10-05 16:44 UTC by eizamaliev

TODO:

 - [ ] Link for model downloading
 - [ ] Perfomance metrics
 - [ ] Accuracy metrics

2020-10-06 11:48 UTC, vladimir-dudnik requested changes

2020-10-06 11:48 UTC, vladimir-dudnik commented on models/public/yolo-v4-tf/accuracy-check.yml
> +models:
please add link in tools/accuracy-checker/configs

2020-10-06 14:41 UTC, eaidova commented on models/public/yolo-v4-tf/accuracy-check.yml
> +        weights: FP32/yolo-v4.bin
these 2 lines should be removed

2020-10-06 14:42 UTC, eaidova commented on models/public/yolo-v4-tf/accuracy-check.yml
> +        subsample_size: 100
please remove subsample_size

2020-10-06 14:43 UTC, eaidova commented on tools/accuracy_checker/accuracy_checker/launcher/tf_launcher.py
> +                    meta_['input_shape'].update({name: data.shape for name, data in infer_input.items()})
```suggestion
                    meta_['input_shape'].update({name: data.shape for name, data in infer_input.items()})
```

2020-10-14 15:45 UTC, IRDonch commented on models/public/yolo-v4-tf/yolo-v4-tf.md
> +1. Download or clone the official [repository](https://github.com/david8862/keras-YOLOv3-model-set) (tested on `ffede5` commit).
This commit seems suspect. The README file in this version doesn't even mention YOLOv4.

2020-10-15 10:20 UTC, IRDonch approved these changes

2020-10-19 15:00 UTC, eaidova commented on models/public/yolo-v4-tf/accuracy-check.yml
> +            threshold: 0.5
why here only 2 metrics, while in the next section 3?

2020-10-19 15:00 UTC, eaidova commented on models/public/yolo-v4-tf/accuracy-check.yml
> +  - name: yolo_v4
```suggestion

  - name: yolo_v4
```

2020-10-19 15:03 UTC, eaidova commented on models/public/yolo-v4-tf/accuracy-check.yml
> +            threshold: '0.5:0.05:0.95'
It is hard to match metric results after evaluation (you have 2 metrics with the same name, but different values)
```suggestion
          - name: AP@0.5 
            type: coco_precision
            max_detections: 100
            threshold: 0.5
          - name: AP@0.5:0.05:0.95 
            type: coco_precision
            max_detections: 100
            threshold: '0.5:0.05:0.95'
```

2020-10-19 21:09 UTC, vladimir-dudnik reviewed
tested all yolo related demos, no one adopted to yolo-v4 yet

2020-10-20 14:14 UTC, eaidova commented on models/public/yolo-v4-tf/accuracy-check.yml
> +            threshold: 0.5
still no explanation where AP0.5:0.05.:0.95 for tf launching?

2020-10-20 14:17 UTC, eaidova commented on models/public/yolo-v4-tf/yolo-v4-tf.md
> +YOLO v4 is a real-time object detection model based on ["YOLOv4: Optimal Speed and Accuracy of Object Detection"](https://arxiv.org/abs/2004.10934) paper It was implemented with Keras\* from this [re
```suggestion
YOLO v4 is a real-time object detection model based on ["YOLOv4: Optimal Speed and Accuracy of Object Detection"](https://arxiv.org/abs/2004.10934) paper. It was implemented with Keras\* from this [repository](https://github.com/david8862/keras-YOLOv3-model-set) and converted to TensorFlow\* framework. This model was pretrained on COCO\* dataset with 80 classes.
```

2020-10-20 14:19 UTC, eaidova commented on models/public/yolo-v4-tf/yolo-v4-tf.md
> +YOLO v4 is a real-time object detection model based on ["YOLOv4: Optimal Speed and Accuracy of Object Detection"](https://arxiv.org/abs/2004.10934) paper It was implemented with Keras\* from this [re
not sure that part about keras grammatically correct, sounds like it is link on fork of keras, not repo with model training

2020-10-21 09:22 UTC, IRDonch commented
Now that #1657 is merged, will you redo `model.yml` to use the original model files?

2020-10-28 15:08 UTC, IRDonch approved these changes

2020-10-28 15:26 UTC, eaidova approved these changes

2020-10-28 17:12 UTC, IRDonch commented
Jenkins please retry a build

2020-10-28 17:15 UTC, IRDonch commented
@eizamaliev Please make the pre-convert script executable.

2020-10-28 21:34 UTC, vladimir-dudnik approved these changes

2020-10-29 08:57 UTC, merged