add fps collecting to tests
openvinotoolkit/open_model_zoo pull request #1631
Opened 2020-10-06 12:26 UTC by ivanvikhrev

Some demos output FPS to console, the change allows to collect this info from logs and store to report during tests.

2020-10-06 13:29 UTC, vladimir-dudnik commented
Jenkins please retry a build

2020-10-06 18:07 UTC, eizamaliev requested changes

2020-10-06 18:07 UTC, eizamaliev commented on demos/tests/run_tests.py
> +                                fps = 'N/A'
```suggestion
                            fps = match_fps.group(0) if match_fps else 'N/A'
```

2020-10-16 08:56 UTC, eizamaliev commented on demos/tests/args.py
> +class NumThreads:
What is the purpose of such classes?
Could we specify `single_option_cases('-nthreads', 1, 2, 4, 8),` or not?

2021-03-29 09:41 UTC, ivikhrev commented
jenkins ok to test

2021-03-29 17:33 UTC, vladimir-dudnik commented
12:50:08  demos/tests/args.py:58: trailing whitespace.

2021-03-29 17:34 UTC, vladimir-dudnik commented
Jenkins please retry a build

2021-12-03 15:54 UTC, closed without merging