Added shufflenet-v2-x1.0 model
openvinotoolkit/open_model_zoo pull request #1653
Opened 2020-10-13 14:13 UTC by Anna-Mironova

2020-10-13 14:53 UTC, Anna-Mironova commented on models/public/shufflenet-v2-x1.0/model.yml
> +quantizable: yes
Removed

2020-10-13 14:54 UTC, eaidova approved these changes

2020-10-13 15:41 UTC, eizamaliev approved these changes

2020-10-14 16:02 UTC, IRDonch requested changes

2020-10-14 16:02 UTC, IRDonch commented on models/public/shufflenet-v2-x1.0/model.yml
> +    source: https://raw.githubusercontent.com/pytorch/vision/227027d5abc8eacb110c93b5b5c2f4ea5dd401d6/torchvision/models/utils.py
We don't normally download Torchvision source files; we have Torchvision as a dependency of the conversion process, and so we can just use `--import-module=torchvision.models`. Is there any reason not to do that in this case?

2020-10-15 14:30 UTC, IRDonch requested changes

2020-10-15 14:30 UTC, IRDonch commented on models/public/shufflenet-v2-x1.0/accuracy-check.yml
> +          - name: acciracy@top5
```suggestion
          - name: accuracy@top5
```

2020-10-16 09:33 UTC, IRDonch approved these changes

2020-10-16 09:34 UTC, merged