Add the handler of open video error in action_recognition demo
openvinotoolkit/open_model_zoo pull request #1793
Opened 2020-11-16 10:51 UTC by anzhella-pankratova

There was no handling of situation when the demo fails to open the input video (one or many). Add the handler of this error to prevent the demo further running.

2020-11-16 15:10 UTC, vladimir-dudnik commented
@anzhella-pankratova please see CI errors:
`16:24:13  Traceback (most recent call last):
16:24:13    File "/home/jenkins/workspace/omz/precommit/demos_ubuntu18@2/src/demos/python_demos/action_recognition/action_recognition.py", line 27, in <module>
16:24:13      from action_recognition_demo.steps import run_pipeline
16:24:13    File "/home/jenkins/workspace/omz/precommit/demos_ubuntu18@2/src/demos/python_demos/action_recognition/action_recognition_demo/steps.py", line 60
16:24:13      self._open_video()
16:24:13                       ^
16:24:13  TabError: inconsistent use of tabs and spaces in indentation`

2020-11-17 10:53 UTC, vladimir-dudnik commented
@anzhella-pankratova please fix pre-commit check issues:
13:42:08  + ./venv/bin/python ./src/ci/check-basics.py
13:42:13  demos/python_demos/action_recognition/action_recognition.py:129: last line doesn't end with a newline character
13:42:13  demos/python_demos/action_recognition/action_recognition_demo/pipeline.py:182: last line doesn't end with a newline character
13:42:13  demos/python_demos/action_recognition/action_recognition_demo/steps.py:180: last line doesn't end with a newline character

2020-11-17 12:55 UTC, Wovchena requested changes
I think we will align help messages with other demos in scope of next task.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition.py
> +    video = [input_path]
We don't need any of this. VideoCapture fails when it encounters empty string. And non-file inputs are valid. For example `0` for camera.

So run_pipeline() could just take `args.input`.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
> +def run_pipeline(video, encoder, decoder, render_fn, loop, decoder_seq_size=16, fps=30):
Put `loop` arg after `video`. They are linked.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
> +    def __init__(self, video_filepath, loop):
Rename `video_filepath` to `input` to be general enough.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
> +                self._video_cycle = iter(self.video)
You should open the video only once. You won't need to iterate over `self.video`.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
> +            exit(1)
There is no need to use both approaches. Either `exit` right from `_open_video()` or just let the exception break the whole demo.
You can even remove `_open_video()` and put its body into init.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
>          self._open_video()
Make `setup()` empty.

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
> +                self._open_video()
```suggestion
```

2020-11-17 12:55 UTC, Wovchena commented on demos/python_demos/action_recognition/action_recognition_demo/steps.py
> +                status, frame = self.cap.read()
Check that new `status` value again and stop if it's false.

2020-11-17 14:46 UTC, anzhella-pankratova commented
@Wovchena Could you check my last commit?

2020-11-17 15:13 UTC, Wovchena approved these changes

2020-11-17 15:30 UTC, merged