Change python segmentation demo
openvinotoolkit/open_model_zoo pull request #1816
Opened 2020-11-20 12:59 UTC by alexmasterdi

This PR is a try to solve issue #411. Features:
1. Now demo can work with files and save results to ouput file.
2. Demo using numpy random to create colors for classes.
3. Users can specify classes and colors.
4. Add flag `use_legend` to add information about accordance class-color to the image.

2020-11-23 07:32 UTC, akorobeinikov commented
Jenkins ok to test

2020-11-24 10:27 UTC, eizamaliev requested changes

2020-11-24 10:27 UTC, eizamaliev commented on demos/python_demos/segmentation_demo/segmentation_demo.py
> +    args.add_argument("-c", "--classes", help="Optional. Path to a text file containing class labels.",
Please, rename it to `--labels`.

2020-11-24 10:27 UTC, eizamaliev commented on demos/python_demos/segmentation_demo/segmentation_demo.py
> +    args.add_argument("-col", "--colors", help="Optional. Path to a text file containing colors for classes.",
```suggestion
    args.add_argument("-c", "--colors", help="Optional. Path to a text file containing colors for classes.",
```

2020-11-24 10:27 UTC, eizamaliev commented on demos/python_demos/segmentation_demo/segmentation_demo.py
> +    args.add_argument("-col", "--colors", help="Optional. Path to a text file containing colors for classes.",
@Wovchena any objections?

2020-11-24 19:07 UTC, eaidova commented on demos/python_demos/segmentation_demo/segmentation_demo.py
> +    classes = get_info_from_file(args.classes)
```
AttributeError: 'Namespace' object has no attribute 'classes'
```

2020-11-30 08:01 UTC, eizamaliev approved these changes

2020-11-30 10:16 UTC, eaidova approved these changes

2020-11-30 16:50 UTC, merged