Added RepVGG models
openvinotoolkit/open_model_zoo pull request #2180
Opened 2021-03-09 10:17 UTC by Anna-Mironova

2021-03-10 12:52 UTC, eaidova commented
jenkins please retry a build

2021-03-10 20:51 UTC, Wovchena approved these changes

2021-03-10 20:52 UTC, Wovchena commented
jenkins please retry a build

2021-03-11 06:17 UTC, Anna-Mironova commented
jenkins please retry a build

2021-03-11 06:21 UTC, Anna-Mironova commented on models/public/repvgg-a0/pre-convert.py
> +        str(args.input_dir / 'convert.py'),
Updated. Removed the use of external script

2021-03-11 10:05 UTC, eaidova approved these changes

2021-03-15 16:57 UTC, IRDonch commented on models/public/repvgg-a0/pre-convert.py
> +    if 'state_dict' in checkpoint:
Shouldn't it be known ahead of time whether this is true? The input checkpoint file is fixed.

2021-03-18 07:41 UTC, vladimir-dudnik reviewed
Is there are any special reasons to add four mostly similar (according to the description) models? Will not it be enough to add only either B0 or B1 variant?

2021-03-18 07:44 UTC, eaidova commented
> Is there are any special reasons to add four mostly similar (according to the description) models? Will not it be enough to add only either B0 or B1 variant?

Different complexity and different accuracy (b3 is SoTA for ImageNet right now), we selected 4 most significant from 12

2021-03-18 10:46 UTC, vladimir-dudnik commented
might be limit to B0 and B3 then?

2021-03-22 14:45 UTC, Anna-Mironova commented on models/public/repvgg-a0/pre-convert.py
> +    if 'state_dict' in checkpoint:
Сondition removed

2021-03-23 06:29 UTC, eaidova commented
Jenkins please retry a build

2021-03-23 09:39 UTC, IRDonch approved these changes

2021-03-23 21:49 UTC, vladimir-dudnik requested changes
could you please add models to test cases?

2021-03-24 08:10 UTC, Anna-Mironova commented
> could you please add models to test cases?

Done

2021-03-24 08:52 UTC, vladimir-dudnik approved these changes

2021-03-24 09:28 UTC, eaidova commented
Jenkins please retry a build

2021-03-24 12:00 UTC, merged