Add a config describing which version of OpenVINO toolkit to use in CI
openvinotoolkit/open_model_zoo pull request #2272
Opened 2021-04-02 16:40 UTC by IRDonch

This will let us upgrade OpenVINO on CI by submitting a PR that edits the config, which will make it easy to test OMZ with new OpenVINO packages, as well as make synchronized project changes if necessary (e.g. changing the Python dependencies).

I used different Python keys for different OSes, because sometimes different
builds are used as the final release for each OS. We might also want to use
different pre-release builds for whatever reason.

[skip-ci]

2021-04-02 16:40 UTC, IRDonch commented
(drafted and CI disabled until the CI side support is enabled)

2021-04-05 11:24 UTC, nignatovsky requested changes

2021-04-05 11:24 UTC, nignatovsky commented on ci/dependencies.yml
> +openvino_linux: '2020.3.394'
```suggestion
openvino_linux: '2021.3.394'
```

2021-04-05 11:24 UTC, nignatovsky commented on ci/dependencies.yml
> +openvino_windows: '2020.3.394'
```suggestion
openvino_windows: '2021.3.394'
```

2021-04-05 11:34 UTC, IRDonch commented on ci/dependencies.yml
> +openvino_linux: '2020.3.394'
Oh, right. :D

2021-04-05 11:36 UTC, IRDonch commented on ci/dependencies.yml
> +openvino_linux: '2020.3.394'
Fixed.

2021-04-06 10:35 UTC, IRDonch commented
Jenkins please retry a build

2021-04-06 10:36 UTC, IRDonch commented
Jenkins please retry a build

2021-04-06 14:43 UTC, vladimir-dudnik approved these changes

2021-04-06 14:44 UTC, nignatovsky approved these changes

2021-04-06 15:09 UTC, merged