Compiled networks support for some demos.
openvinotoolkit/open_model_zoo pull request #2279
Opened 2021-04-06 15:33 UTC by ivikhrev

Added compiled networks support in model wrappers for cpp demos.

TODO:
- [ ] Add support for yolo model wrapper in object detection demo.
- [ ] Validate models in models.lst for each demo.

2021-04-13 18:25 UTC, ivikhrev commented
Jenkins please retry a build

2021-04-14 09:50 UTC, eizamaliev requested changes

2021-04-14 09:50 UTC, eizamaliev commented on demos/common/cpp/models/src/model_base.cpp
> +    isNetworkCompiled = fileExt(modelFileName) == "blob";
You should determine model "type" as soon as you get filename - in `ModelBase::prepareNetwork` method or even in constructor. It also will prevent reading network.

2021-04-30 11:13 UTC, vladimir-dudnik commented
@ivikhrev seems there are merge artifacts:
13:37:09    c:\jenkins\workspace\demos_windows10ce29c7ab\src\demos\common\cpp\pipelines\src\async_pipeline.cpp(77): error C2317: 'try' block starting on line '77' has no catch handlers [C:\jenkins\workspace\demos_windows10ce29c7ab\build\common\cpp\pipelines\pipelines.vcxproj]

2021-04-30 11:40 UTC, ivikhrev commented
@fzhar  I've picked out general part from functions `prepareInputsOutputs` and `checkCompiledNetworkInputsOutputs` and made from it one function `checkInputOutputs`. Now configuring and checking inputs & outputs are done separately.

2021-04-30 22:34 UTC, fzhar commented
I'd like to change current implementation of prepareInputsOutputs / checkInputsOutputs:
1. checkInputOutputs should perform universal checks suitable for any model - precision, number of inputs, etc. Those custom parameters should be passed to that function as arguments or template arguments. PrepareInputsOutputs/сheckCompiledNetworkInputsOutputs will call this function with custom arguments.
2. Extract filling names arrays code from checkInputsOutputs to separate function (let's call it, for instance findIONames). This function should fill inputsNames and outputsNames in proper order.
3. Preferably (not necessary, but...) create enums for indexes in inputsNames and outputsNames, For instance, image input should always have index 0 in names table, let's create enum item for it.
4. Split process of preparing I/O and checking I/O into several stages. I.e., instead of calling only prepareInputsOutput or checkCompiledModelInputsOutputs, loadModel should call several function in sequence:
- findIONames
- prepareInputsOutputs (if we use CNNNetwork. Otherwise it should be skipped. This function should use already found names of inputs and outputs)
- checkInputsOutputs (for both compiled and IR/CNNNetwork cases). This function takes inputsInfo, inputsNames and outputsInfo , outputsNames as input and perform necessary checks. Generally should call universal checking function with proper args (see pt.1) and then do some custom checks for this particular model (if required). Custom checks should use already found IO names, if it's feasible.

All described above is a general plan, but not a strict requirement for this commit. This plan is discussible. If we cannot finish all these changes in time, we may use current implementation for now (as it is good as POC), but implement changes listed above in separate commit.

2021-05-24 11:46 UTC, ivikhrev commented
Jennkins please retry a build

2021-05-25 10:08 UTC, vladimir-dudnik commented
13:05:53  /jenkins/workspace/omz/precommit/demos_ubuntu18@2/src/demos/common/cpp/models/include/models/model_base.h:142:15: error: cannot bind non-const lvalue reference of type ‘std::_Rb_tree_const_iterator<std::pair<const std::__cxx11::basic_string<char>, InferenceEngine::TensorDesc> >&’ to an rvalue of type ‘std::map<std::__cxx11::basic_string<char>, InferenceEngine::TensorDesc>::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const std::__cxx11::basic_string<char>, InferenceEngine::TensorDesc> >}’

2021-05-25 13:12 UTC, fzhar commented on demos/common/cpp/models/include/models/model_base.h
> +        const std::string type;
Please use enum instead of string

2021-05-25 14:31 UTC, ivikhrev commented on demos/common/cpp/models/include/models/model_base.h
> +        // Keep proper input namaes order
fixed

2021-05-25 14:31 UTC, ivikhrev commented on demos/common/cpp/models/include/models/model_base.h
> +            InferenceEngine::ResizeAlgorithm algo = InferenceEngine::ResizeAlgorithm::RESIZE_BILINEAR)
removed

2021-12-03 15:54 UTC, closed without merging