Replace IE exceptions
openvinotoolkit/open_model_zoo pull request #2343
Opened 2021-04-23 17:39 UTC by ivikhrev

Replaced IE exceptions with std::runtime_error.

2021-04-25 18:05 UTC, Wovchena approved these changes

2021-04-26 09:37 UTC, IRDonch requested changes

2021-04-26 09:37 UTC, IRDonch commented on demos/common/cpp/utils/include/utils/ocv_common.hpp
> +       throw std::runtime_error("The number of channels for net input and image must match");
```suggestion
        throw std::runtime_error("The number of channels for net input and image must match");
```

2021-04-26 12:44 UTC, IRDonch approved these changes

2021-04-26 13:36 UTC, merged