Demo for multi-speaker TTS model
openvinotoolkit/open_model_zoo pull request #2360
Opened 2021-04-29 08:17 UTC by a-a-egorovich

2021-04-29 10:59 UTC, vladimir-dudnik commented
Jenkins please retry a build

2021-04-29 20:00 UTC, eaidova commented
Jenkins ok to test

2021-04-29 20:11 UTC, vladimir-dudnik commented
23:01:29  demos/text_to_speech_demo/python/models/forward_tacotron_ie.py:309: new blank line at EOF.

2021-04-30 13:28 UTC, Wovchena commented on demos/text_to_speech_demo/python/text_to_speech_demo.py
> +                       help="Ordinal number of the speaker in embeddings array for multi-speaker model.",
It's worth noting that -1 activates Multi-speaker TTS parameters selection window

Please, update readme listing help message with new args

2021-04-30 18:02 UTC, Wovchena approved these changes

2021-05-04 16:52 UTC, IRDonch requested changes

2021-05-04 16:52 UTC, IRDonch commented on demos/text_to_speech_demo/python/text_to_speech_demo.py
> +                      help="Ordinal number of the speaker in embeddings array for multi-speaker model."
```suggestion
                      help="Ordinal number of the speaker in embeddings array for multi-speaker model. "
```

2021-05-05 07:38 UTC, a-a-egorovich commented on demos/text_to_speech_demo/python/text_to_speech_demo.py
> +                      help="Ordinal number of the speaker in embeddings array for multi-speaker model."
Done

2021-05-05 09:41 UTC, IRDonch approved these changes

2021-05-05 09:41 UTC, merged