update documentation
openvinotoolkit/open_model_zoo pull request #2367
Opened 2021-04-29 23:24 UTC by vladimir-dudnik

update OMZ docs

2021-05-07 09:13 UTC, andrew-zaytsev requested changes

2021-05-07 09:38 UTC, vladimir-dudnik commented on demos/bert_question_answering_demo/python/README.md
> +Pre-trained models, supported by demo listed in [models.lst](./models.lst) file, located at each demo folder.
instead providing pseudo path `<omz_dir>/demos/bert_question_answering_demo` can we just remove link and rely on what we said at the end of phrase `located at each demo folder`

2021-05-07 10:47 UTC, vladimir-dudnik commented on models/intel/index.md
added refs to demos, downloader and public models

2021-05-07 10:57 UTC, vladimir-dudnik commented on demos/README.md
> +
added refs to intel and public models

2021-05-07 13:55 UTC, vladimir-dudnik commented on demos/3d_segmentation_demo/python/README.md
> +## Preparing to run
done

2021-05-07 13:55 UTC, vladimir-dudnik commented on demos/bert_question_answering_embedding_demo/python/README.md
> +Pre-trained models, supported by demo listed in [models.lst](./models.lst) file, located at each demo folder.
fixed

2021-05-07 13:56 UTC, vladimir-dudnik commented on demos/bert_named_entity_recognition_demo/python/README.md
> +Pre-trained models, supported by demo listed in [models.lst](./models.lst) file, located at each demo folder.
fixed

2021-05-11 17:23 UTC, tsavina commented on demos/object_detection_demo/cpp/README.md
> +If labels file is used, it should correspond to model output. Demo treat labels, listed in the file, to be indexed from 0, one line - one label (i.e. very first line contains label for ID 0). Note th
i.e. ---> that is

2021-05-11 21:11 UTC, vladimir-dudnik commented on demos/README.md
> +> **NOTE:** Inference Engine HDDL plugin are available in [proprietary](https://software.intel.com/en-us/openvino-toolkit) distribution only.
done

2021-05-11 21:11 UTC, vladimir-dudnik commented on demos/bert_question_answering_demo/python/README.md
> +The "small" variants of these are so called "distilled" models, which originated from the BERT Large but substantially smaller and faster.
done

2021-05-11 21:11 UTC, vladimir-dudnik commented on demos/bert_question_answering_embedding_demo/python/README.md
> +from the command-line match the actual network inputs.
done

2021-05-11 21:11 UTC, vladimir-dudnik commented on demos/bert_question_answering_embedding_demo/python/README.md
> +Be sure that the original model converted by Model Optimizer with reshape option.
done

2021-05-11 21:11 UTC, vladimir-dudnik commented on demos/classification_demo/cpp/README.md
>  For example, use the following command line command to run the application:
done

2021-05-11 21:12 UTC, vladimir-dudnik commented on demos/face_detection_mtcnn_demo/python/README.md
> +Run the application with the `-h` option to see available command line parameters:
done

2021-05-11 21:12 UTC, vladimir-dudnik commented on demos/formula_recognition_demo/python/README.md
> +* Use `q` button to quit from program
done

2021-05-11 21:12 UTC, vladimir-dudnik commented on demos/handwritten_text_recognition_demo/python/README.md
> +For example, if we want to restrict the output characters to only digits and hyphens, we need to provide the path to the designated character file, e.g. `digit_hyphen.txt`. Then the script will perfo
done

2021-05-11 21:12 UTC, vladimir-dudnik commented on demos/human_pose_estimation_3d_demo/python/README.md
> +Refer to [Open Model Zoo Demos](../../README.md), for instructions on how to build it and prepare the environment for running the demo.
done

2021-05-11 21:13 UTC, vladimir-dudnik commented on demos/interactive_face_detection_demo/cpp/README.md
> +4. The application performs up to five simultaneous inferences, using the Age/Gender, Head Pose, Emotions, Facial Landmarks and Anti-spoof detection networks if they are specified in the command line
done

2021-05-11 21:13 UTC, vladimir-dudnik commented on demos/interactive_face_detection_demo/cpp_gapi/README.md
> +2. G-API pipeline gets a video/image/camera like a source using the OpenCV VideoCapture.
done

2021-05-11 21:13 UTC, vladimir-dudnik commented on demos/multi_channel_object_detection_demo_yolov3/cpp/README.md
> +This demo provides an multi channel inference pipeline for YOLO v3 Object Detection network.
done

2021-05-11 21:13 UTC, vladimir-dudnik commented on demos/object_detection_demo/cpp/README.md
> +On the start-up, the application reads command line parameters and loads a network to the Inference Engine. Upon getting a frame from the OpenCV VideoCapture it performs inference and displays the re
done

2021-05-11 21:13 UTC, vladimir-dudnik commented on demos/object_detection_demo/cpp/README.md
> +If labels file is used, it should correspond to model output. Demo treat labels, listed in the file, to be indexed from 0, one line - one label (i.e. very first line contains label for ID 0). Note th
done

2021-05-11 21:51 UTC, tsavina approved these changes

2021-05-12 23:12 UTC, vladimir-dudnik commented
Jenkins please retry a build

2021-05-13 00:09 UTC, vladimir-dudnik commented
Jenkins please retry a build

2021-05-13 01:03 UTC, merged