Model for ultrasound simulation
openvinotoolkit/open_model_zoo pull request #2420
Opened 2021-05-21 07:56 UTC by Rakshith2597

Submitting model for breast ultrasound simulation.

This is part of the project MIRIAD: Many Incarnations of Screening of Radiology for High Throughput Disease Screening via Multiple Instance Reinforcement Learning with Adversarial Deep Neural Networks, sponsored by INTEL TECHNOLOGY INDIA PVT. LTD.

Principal Investigators:

Dr Debdoot Sheet (PI), Dr Nirmalya Ghosh (Co-PI)
Department of Electrical Engineering
Indian Institute of Technology Kharagpur

Dr Ramanathan Sethuraman (Co-PI)
Intel Technology India Pvt. Ltd.

2021-05-21 09:24 UTC, vladimir-dudnik requested changes
we expect contributor will provide all required legal information (model and dataset license, implement accuracy validation support in accuracy-checker and provide corresponding configuration file, implement demo to showcase basic model work)

2021-05-21 09:24 UTC, vladimir-dudnik commented on models/public/breast_ultrasound_simulation/README.md
> +Segmentation masks from [INbreast](http://medicalresearch.inescporto.pt/breastresearch/index.php/Get_INbreast_Database) dataset is used to generate stage 0 simulation results for breast ultrasound.
can't access specified link - The requested URL was not found on this server.

2021-05-21 09:24 UTC, vladimir-dudnik commented on models/public/breast_ultrasound_simulation/README.md
> +The network is trained on [IVUS](http://www.cvc.uab.es/IVUSchallenge2011/dataset.html) dataset. Data augmentation is applied as explain in [1,2,3] and images are processed by [stage 0](https://in.mat
can't fine dataset license information by this link

2021-05-21 09:24 UTC, vladimir-dudnik commented on models/public/breast_ultrasound_simulation/README.md
> +## Publications
Legal Information section is missed. It should specify model license

2021-05-21 09:24 UTC, vladimir-dudnik commented on models/public/breast_ultrasound_simulation/README.md
> +
Accuracy section is missed. You need specify what accuracy model should demonstrate on validation set, what accuracy metric is measured, and how it is computed

2021-05-21 09:24 UTC, vladimir-dudnik commented on models/public/breast_ultrasound_simulation/README.md
> +## **Input and Output**
There should be separate sections, Input and Output, to describe expected format of model's input and output blobs

2021-05-21 09:25 UTC, vladimir-dudnik commented
cc @yssemaev

2021-05-24 07:30 UTC, yssemaev commented
Hi,
The link is not working for me: http://www.cvc.uab.es/IVUSchallenge2011/dataset.htm

2021-12-03 15:54 UTC, closed without merging