Latency logging for every stage of pipeline
openvinotoolkit/open_model_zoo pull request #2466
Opened 2021-06-02 17:41 UTC by fzhar

2021-06-02 21:36 UTC, vladimir-dudnik commented
when input is single JPEG image decoding time is nan

2021-06-04 11:50 UTC, eizamaliev requested changes

2021-06-04 11:50 UTC, eizamaliev commented on demos/common/cpp/pipelines/src/async_pipeline.cpp
> +                this->inferenceMetrics.update(startTime);
```suggestion
                inferenceMetrics.update(startTime);
```
I'd prefer using `this` everywhere, but ... :)

2021-06-04 11:50 UTC, eizamaliev commented on demos/object_detection_demo/cpp/main.cpp
> +        slog::info << slog::endl << "Avg time:\n";
```suggestion
        slog::info << slog::endl << "Average time:\n";
```

2021-06-04 11:52 UTC, eizamaliev commented
Would you add renderer metrics in other Pipeline\* demos in this PR?

2021-06-04 17:03 UTC, fzhar commented
> Would you add renderer metrics in other Pipeline* demos in this PR?

As we've agreed before, these measurements will be implemented for object_detection_demo only in this PR, other demos will be modified in separate PRs

2021-06-09 12:04 UTC, Wovchena approved these changes

2021-06-09 12:31 UTC, vladimir-dudnik approved these changes

2021-06-09 13:33 UTC, eizamaliev approved these changes

2021-06-09 14:35 UTC, merged