add labeler for 3d party changes
openvinotoolkit/open_model_zoo pull request #2596
Opened 2021-07-14 10:08 UTC by generalova-kate

2021-07-14 14:31 UTC, eizamaliev requested changes

2021-07-14 14:31 UTC, eizamaliev commented on .github/labeler.yml
> +dependency_changes:
Please, use existing label `dependency`

2021-07-15 06:30 UTC, generalova-kate commented on .github/labeler.yml
> +dependency_changes:
```suggestion
dependencies:
```

2021-07-15 10:52 UTC, eizamaliev approved these changes

2021-07-16 07:35 UTC, eaidova commented
Jenkins please retry a build

2021-07-16 08:37 UTC, vladimir-dudnik commented
10:36:41  running yamllint...
10:36:47  ./.github/labeler.yml
10:36:47    4:16      error    syntax error: expected alphabetic or numeric character, but found '*' (syntax)
10:36:47  
10:36:47  ./.github/workflows/labeler.yml
10:36:47    3:1       error    wrong indentation: expected 2 but found 0  (indentation)
10:36:47    9:5       error    wrong indentation: expected 6 but found 4  (indentation)
10:36:47    12:26     error    no new line character at the end of file  (new-line-at-end-of-file)
10:36:47  
10:36:47  running flake8...
10:36:57  running documentation checks...
10:36:58  .github/workflows/labeler.yml:12: last line doesn't end with a newline character
10:36:58  CODEOWNERS:5: last line doesn't end with a newline character

2021-07-16 09:09 UTC, generalova-kate commented
Jenkins please retry a build

2021-07-16 09:12 UTC, generalova-kate commented
Jenkins please retry a build

2021-07-22 15:35 UTC, merged