Retinaface resnet50 (to release)
openvinotoolkit/open_model_zoo pull request #2667
Opened 2021-08-10 09:55 UTC by fzhar

Merging separately to release branch

2021-08-10 10:02 UTC, eizamaliev requested changes

2021-08-10 10:02 UTC, eizamaliev commented on demos/object_detection_demo/cpp/models.lst
> +retinaface-resnet50-pytorch
Add the 
```
For -at=retinaface-pytorch
```
here.
Also add it to develop branch

2021-08-10 10:02 UTC, eizamaliev commented
cc @vladimir-dudnik

2021-08-10 18:45 UTC, fzhar commented
Jenkins please retry a build

2021-08-10 21:51 UTC, vladimir-dudnik commented
Jenkins please retry a build

2021-08-11 08:16 UTC, eizamaliev approved these changes

2021-08-11 17:05 UTC, merged