Optimize yolov4 model postprocessing for python detection demo
openvinotoolkit/open_model_zoo pull request #2725
Opened 2021-09-02 21:43 UTC by akorobeinikov

Optimize yolov4 model (v4 and v4 tiny) postprocessing for detection demo, by using flatten operation and apply sigmoid function to all boxes at the same time.
**Speed up**:
1. For YoloV4: `2.4 -> 3.7 fps` It's x1.55.
2. For YoloV4-tiny: `25 -> 50+ fps` It's x2.

The calculations were carried out on the CPU `Intel® Core™ i7-8700 CPU` and on video with resolution `1280 × 720`.

2021-09-07 09:38 UTC, eizamaliev requested changes

2021-09-07 09:38 UTC, eizamaliev commented on demos/common/python/models/yolo.py
> +            class_probabilities = sigmoid(prediction[:, params.coords + 1:].flatten())
```suggestion
            class_probabilities = sigmoid(prediction[:, 5:].flatten())
```
The `YoloParams::params` field is sort of redundant

2021-09-07 09:38 UTC, eizamaliev commented on demos/common/python/models/yolo.py
> +                bbox = prediction[:, :params.coords][obj_ind]
```suggestion
                bbox = prediction[:, :4][obj_ind]
```
See comment above

2021-09-07 11:20 UTC, vladimir-dudnik commented
@akorobeinikov would it make sense to do the same on AC side, so we can estimate if this optimization affects accuracy?

2021-09-07 13:59 UTC, vladimir-dudnik commented
Jenkins please retry a build

2021-09-07 15:55 UTC, akorobeinikov commented
> would it make sense to do the same on AC side, so we can estimate if this optimization affects accuracy?

In my opinion, it is don't make sense, because this optimizations haven't any new operations, it only reorder steps of postprocessing for speed up, but new version is equivalent to old version and optimization can affect accuracy only if there are  bugs in code. Also I checked accuracy of boxes when tested performance on single images and accuracy is the same (this is not indicative, but at least something). We can do the same on AC side for optimization, but I think it is don't make sense to change AC yolo structure for little optimization, because AC don't oriented on speed.

2021-09-07 21:29 UTC, vladimir-dudnik commented
> > would it make sense to do the same on AC side, so we can estimate if this optimization affects accuracy?
> 
> In my opinion, it is don't make sense, because this optimizations haven't any new operations,
That is exactly what might be tested with AC. And additionally, improving speed for AC validation is important too.

2021-09-08 10:31 UTC, eizamaliev approved these changes

2021-09-08 11:50 UTC, merged