add cpp noise_suppression_demo
openvinotoolkit/open_model_zoo pull request #2875
Opened 2021-11-08 19:30 UTC by krodyush

cpp demo to run noise suppression

2021-11-10 10:13 UTC, Wovchena requested changes
Add a test for the demo

2021-11-10 10:13 UTC, Wovchena commented on demos/noise_suppression_demo/cpp/main.cpp
> +{
```suggestion
bool write_wav(const std::string& file_name, const std::vector<short>& wave, const RiffWaveHeader& wave_header) {
```
We place brackets on the same line

2021-11-10 10:13 UTC, Wovchena commented
Jenkins please retry a build

2021-11-10 10:18 UTC, Wovchena commented
Useful bot :)

2021-11-10 10:39 UTC, Wovchena commented
Jenkins ok to test

2021-11-10 10:57 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +typedef std::chrono::high_resolution_clock Time;
ok

2021-11-10 11:06 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +    if (0 != memcmp(&p_wave_header->riff_tag, "RIFF", 4))
This code is taken from existed openvino sample https://docs.openvino.ai/latest/openvino_inference_engine_samples_speech_libs_and_demos_Offline_speech_recognition_demo.html.

2021-11-10 11:22 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +        std::cout << state_size*1e-6 << "M params in all states" << std::endl;
Because this is useful information answer to the question "how big state is?" The size of patch shows input data slicing granularity.

2021-11-10 11:25 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +            std::cout << inp_state_name << "<-" << out_state_name << " " << tensor_size << " params" << std::endl;
Did not catch. Where is "python"?

2021-11-10 11:38 UTC, krodyush commented on demos/noise_suppression_demo/cpp/README.md
> +    -o OUTPUT    Required. Path to a output WAV file.
ok

2021-11-10 11:41 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +        InferenceEngine::OutputsDataMap outputs = network.getOutputsInfo();
removed. Thanks!

2021-11-10 11:43 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +DEFINE_int32(delay, 0, delay_message);
remove delay to be aligned with python

2021-11-10 11:47 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +        float scale = 1.0f/SHRT_MAX;
ok

2021-11-10 11:48 UTC, krodyush commented on demos/noise_suppression_demo/cpp/README.md
> +    -delay DELAY Required. delay in samples that model adds during processing
remove delay to be aligned with python

2021-11-10 13:25 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +        std::cerr << "fail to read " << file_name << std::endl;
ok

2021-11-10 13:25 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +    FILE *inp_wave = fopen(file_name.c_str(), "rb");
close file before exit

2021-11-10 18:41 UTC, vladimir-dudnik commented
19:27:23  demos/noise_suppression_demo/cpp/main.cpp:187: trailing whitespace.

2021-11-13 07:41 UTC, krodyush commented on demos/noise_suppression_demo/cpp/main.cpp
> +#include <inference_engine.hpp>
may be it makes sense to switch to new API when precomit will be ready for this?

2021-11-15 05:35 UTC, Wovchena commented on demos/noise_suppression_demo/cpp/main.cpp
> +#include <inference_engine.hpp>
No. There are bugs in new API. The earlier you find and report them the better

2021-11-18 17:04 UTC, Wovchena commented
OMZ branching strategy has changed: https://github.com/openvinotoolkit/open_model_zoo/pull/2905. Retarget to master.

2021-11-26 10:40 UTC, Wovchena commented on demos/noise_suppression_demo/cpp/main.cpp
> +#include <inference_engine.hpp>
It turned out we don't have a commitment to use ov 2.0 in this release. Never mind

2021-11-26 10:48 UTC, Wovchena commented
https://github.com/openvinotoolkit/open_model_zoo/pull/2907

2021-11-26 10:48 UTC, closed without merging