Check working tests
openvinotoolkit/open_model_zoo pull request #3221
Opened 2022-02-15 08:06 UTC by VoronovaIntern

2022-02-15 12:38 UTC, vladimir-dudnik commented
@VoronovaIntern please rebase, also list which tests still disabled (and why)

2022-02-16 13:39 UTC, VoronovaIntern commented
tests are falling
CPP dependences cannot be built in human_pose_estimation_3d_demo and speech_recognition_deepspeech_demo  
Python:
- [ ] human_pose_estimation_3d_demo : ImportError: cannot import name 'extract_poses' from 'pose_extractor' (unknown location)
- [ ] speech_recognition_deepspeech_demo : No module named 'ctcdecode_numpy'
- [ ] bert_named_entity_recognition_demo : IndexError: list index out of range
- [ ]  image_retrieval_demo : Need to Put image_retrieval_arg import back

2022-02-16 17:40 UTC, vladimir-dudnik commented
Jenkins please retry a build

2022-02-17 14:27 UTC, VoronovaIntern commented
added several fails:

- [ ] instance_segmentation_demo : division by zero
- [ ]  social_distance_demo person-reidentification-retail-0277 : fails with exit code -6
- [ ]  object_detection_demo face-detection-0205:  fails with exit code -11

2022-02-28 23:03 UTC, vladimir-dudnik commented
Jenkins please retry a build

2022-03-01 22:08 UTC, vladimir-dudnik commented
failed at person-reidentification-retail-0287, but not reproduced locally (at least on video)

2022-03-01 22:29 UTC, vladimir-dudnik commented
Jenkins please retry a build

2022-03-02 09:37 UTC, VoronovaIntern commented
Now commented python demos which cannot find modules

- [ ] speech_recognition_deepspeech_demo (No module named 'ctcdecode_numpy')
- [ ] image_retrieval_demo (TODO: Put image_retrieval_arg import back) 
- [ ] human_pose_estimation_3d_demo (cannot import name 'extract_poses' from 'pose_extractor' (unknown location))

2022-03-02 13:28 UTC, vladimir-dudnik commented
@nignatovsky it seems to be some CI env issue when python demos can't find modules. Do we add them to PYTHONPATH as it described in these demo description?

2022-03-02 14:00 UTC, anzhella-pankratova commented
@VoronovaIntern you have some not related to tests changes in the PR. Could you please remove it?

2022-03-02 17:06 UTC, VoronovaIntern commented
I ran tests locally and only demo with person-reidentification-retail-0287 and 0288 on version 612, everything works

2022-03-02 19:18 UTC, Wovchena commented
... after you resolve the conflict :)

2022-03-03 14:36 UTC, vladimir-dudnik commented
@VoronovaIntern please rebase

2022-03-03 14:48 UTC, VoronovaIntern commented
Jenkins please retry a build

2022-03-03 14:58 UTC, anzhella-pankratova requested changes

2022-03-03 14:58 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +    CppDemo(name='gaze_estimation_demo', implementation='cpp_gapi',
The repetition, need to remove

2022-03-03 14:58 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +    CppDemo(name='gesture_recognition_demo', implementation='cpp_gapi',
The repetition, need to remove

2022-03-03 14:58 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +    CppDemo(name='face_detection_mtcnn_demo', implementation='cpp_gapi',
The repetition, need to remove

2022-03-03 14:58 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +    CppDemo(name='interactive_face_detection_demo', implementation='cpp_gapi',
The repetition, need to remove

2022-03-03 14:58 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +PYTHON_DEMOS = [
```suggestion
```

2022-03-03 14:58 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +                ModelArg('instance-segmentation-security-0091'), # Slow model
```suggestion
                # ModelArg('instance-segmentation-security-0091'), # Slow model
```

2022-03-03 16:21 UTC, anzhella-pankratova approved these changes

2022-03-04 11:35 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +
```suggestion
```

2022-03-04 11:39 UTC, VoronovaIntern commented on demos/tests/cases.py
> +
Done

2022-03-04 13:35 UTC, VoronovaIntern commented
Problem demos and models:

- [ ] social_distance_demo ( person-reidentification-retail-0286 and 0288)
- [ ] action_recognition_demo ( action-recognition-0001) monitors_extension wasn't found
- [ ] human_pose_estimation_3d_demo  Module 'pose_extractor' not found
- [ ] speech_recognition_deepspeech_demo No module named 'ctcdecode_numpy'
- [ ] whiteboard_inpainting_demo ( instance-segmentation-security-0091) Slow model

2022-03-04 16:07 UTC, merged