Quantizer engine
openvinotoolkit/open_model_zoo pull request #3293
Opened 2022-02-24 13:48 UTC by valeriya-morozova

2022-02-24 14:02 UTC, vladimir-dudnik commented
Jenkins please retry a build

2022-02-24 14:40 UTC, vladimir-dudnik commented
Jenkins please retry a build

2022-02-24 15:57 UTC, jkamelin requested changes

2022-02-24 15:57 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/quantize_engine/quantizer.py
> +            _requested_precisions = _common.KNOWN_PRECISIONS
```suggestion
            _requested_precisions = _common.KNOWN_QUANTIZED_PRECISIONS.keys()
```

2022-02-24 15:57 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/quantize_engine/quantizer.py
> +        unknown_precisions = _requested_precisions - _common.KNOWN_PRECISIONS
```suggestion
        unknown_precisions = _requested_precisions - _common.KNOWN_QUANTIZED_PRECISIONS.keys()
```

2022-02-24 15:57 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/omz_quantizer.py
> +            precisions_to_send = quantizer.requested_precisions if args.precisions else quantizer.requested_precisions & model.precisions
We should send precisions requested by user even if they are not supported

2022-02-25 07:37 UTC, SDxKeeper commented on tools/model_tools/src/openvino/model_zoo/omz_quantizer.py
> +        quantizer = Quantizer(args.python, args.precisions, args.output_dir, args.model_dir, args.pot, args.dry_run)
@valeriya-morozova where do you get args from ? Is it latest version?

2022-02-25 07:42 UTC, jkamelin requested changes

2022-02-25 07:42 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/omz_quantizer.py
> -            sys.exit('--dataset_dir must be specified.')
Please restore this check

2022-02-25 09:29 UTC, jkamelin commented
Jenkins ok to test

2022-02-25 10:31 UTC, jkamelin requested changes

2022-02-25 10:31 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/omz_quantizer.py
> +
If you move this to `Quantizer` it's not needed here anymore, it will brake `--print_all` option.

2022-02-25 12:10 UTC, eaidova commented on tools/model_tools/src/openvino/model_zoo/quantize_engine/quantizer.py
> +    def pot_cmd_prefix(self, value: str = None):
for me from API user perspective this place looks slightly confusing. The class assumes that pot path already predefined explicitly or required to set explicitly to None to trigger executable check behavior. Maybe no need to use setter here and explicitly use method for setting?

2022-02-28 05:24 UTC, eaidova commented on tools/model_tools/src/openvino/model_zoo/quantize_engine/quantizer.py
> +import json
please add license header

2022-02-28 12:27 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/quantize_engine/quantizer.py
> +# Copyright (c) 2020-2021 Intel Corporation
```suggestion
# Copyright (c) 2022 Intel Corporation
```

2022-02-28 12:27 UTC, jkamelin commented on tools/model_tools/src/openvino/model_zoo/quantize_engine/__init__.py
> +# Copyright (c) 2020-2021 Intel Corporation
```suggestion
# Copyright (c) 2022 Intel Corporation
```

2022-02-28 12:34 UTC, jkamelin approved these changes

2022-02-28 12:36 UTC, eaidova approved these changes

2022-02-28 15:18 UTC, merged