Add ability to test demos of specific implementation.
openvinotoolkit/open_model_zoo pull request #3319
Opened 2022-03-01 19:40 UTC by ivikhrev

For -`-demos` argument `gapi, cpp, python` values were added, which enable testing demos of corresponding implementation. Added exception in case of empty list of demos to test.

2022-03-02 09:25 UTC, Wovchena requested changes

2022-03-02 12:23 UTC, anzhella-pankratova approved these changes
The introduction of performance scope affects this PR: if `--demos object_detection_demo/python` is passed, only test cases from performance_cases will be taken.  

Please, could you fix it in this PR:  in performance_cases when we modify demos from `BASE` dictionary, we should take deepcopy of value, like `deepcopy(BASE['object_detection_demo/python'])`

2022-03-02 15:12 UTC, ivikhrev commented on demos/tests/cases.py
> +DEMOS_PER_IMPL = { 'gapi' : GAPI_DEMOS, 'cpp' : CPP_DEMOS, 'python' : PYTHON_DEMOS }
done

2022-03-02 15:12 UTC, ivikhrev commented on demos/tests/run_tests.py
> +            names_of_demos_to_test = [demo.subdirectory for demo in demos_of_specific_impls]
done

2022-03-02 15:12 UTC, ivikhrev commented on demos/tests/run_tests.py
> +        'For testing demos of specific implementation pass one (or more) of the next values: gapi, cpp, python.')
done

2022-03-02 15:23 UTC, anzhella-pankratova commented on demos/tests/cases.py
> +    IMPLEMETATION_TYPES = set()
```suggestion
    IMPLEMENTATION_TYPES = set()
```

2022-03-02 15:24 UTC, ivikhrev commented on demos/tests/cases.py
> +    IMPLEMETATION_TYPES = set()
yeah, thanks

2022-03-02 16:26 UTC, anzhella-pankratova commented on demos/tests/run_tests.py
> +                names_of_demos_to_test.update({demo.subdirectory for demo in DEMOS if demo.implementation == impl})
the simplification:
```suggestion
            names_of_demos_to_test = {demo.subdirectory for demo in DEMOS if demo.implementation in names_of_demos_to_test}
```

2022-03-02 19:16 UTC, merged

2022-03-03 08:12 UTC, Wovchena commented
@ivikhrev, now you need to add 3 jobs to precommits running cpp, gapi and python separately, keeping old one for now