Fix yolo detection results for models created with the 2022.1 model optimizer
openvinotoolkit/open_model_zoo pull request #3463
Opened 2022-04-14 20:00 UTC by mempf

Yolo models converted with the 2022.1 model optimizer have a different output shape (NHWC) compared to ones converted with an earlier version (NCHW).

The current output processing for yolo in the C++ examples assumes the output tensors use NCHW layout. This PR uses the PrePostProcessor to convert the output tensor to the expected shape regardless which version of the model optimizer was used to create it.

Fixes: https://github.com/openvinotoolkit/open_model_zoo/issues/3462

2022-04-15 20:13 UTC, vladimir-dudnik commented
Jenkins please retry a build

2022-07-29 13:38 UTC, Wovchena requested changes
Thank you for the patch! The problem with it is that it breaks for yolo-v1:
```bat
.\intel64\Release\object_detection_demo.exe -i "C:\Users\vzlobin\OneDrive - Intel Corporation\a\videos\896x512AACHEN 4ConvertedFliped.mov" -at yolo -m C:\Users\vzlobin\Downloads\d\old\yolo-v1-tiny-tf\FP32\yolo-v1-tiny-tf.xml
MFX: Unsupported extension: C:\Users\vzlobin\OneDrive - Intel Corporation\a\videos\896x512AACHEN 4ConvertedFliped.mov
[ INFO ] OpenVINO
[ INFO ]        version: 2022.1.0
[ INFO ]        build: 2022.1.0-7019-cdb9bec7210-releases/2022/1
[ INFO ] Reading model C:\Users\vzlobin\Downloads\d\old\yolo-v1-tiny-tf\FP32\yolo-v1-tiny-tf.xml
[ INFO ] Model name: yolo-v1-tiny-tf
[ INFO ]        Inputs:
[ INFO ]                input_1, f32, {1,3,416,416}, [...]
[ INFO ]        Outputs:
[ INFO ]                conv2d_9/BiasAdd/YoloRegion, f32, {1,21125}, [...]
[ WARNING ] Automatically detected layout '[N,C,H,W]' for input 'input_1' will be used.
[ ERROR ] Check 'ov::layout::utils::is_compatible(layout, output.get_partial_shape())' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\core\src\layout.cpp:623:
Can't set layout for Parameter/Result conv2d_9/BiasAdd/YoloRegion/sink_port_0[0]:f32{1,21125}: layout [N,C,H,W] is not compatible with shape {1,21125}
```
Will you fix it?

2022-07-29 15:25 UTC, Wovchena approved these changes

2022-07-29 15:35 UTC, eaidova approved these changes

2022-07-29 15:35 UTC, merged

2022-07-29 18:08 UTC, mempf commented
Thank you @Wovchena and @eaidova for getting this reviewed and merged.