Add Model API to requirements.txt
openvinotoolkit/open_model_zoo pull request #3570
Opened 2022-10-21 16:38 UTC by helena-intel

This PR adds Model API to demo requirements.txt, so users do not need to install Model API manually anymore (which requires going to a different page and following not-trivial instructions).

2022-10-23 08:00 UTC, Wovchena requested changes

2022-10-24 16:10 UTC, helena-intel commented on demos/requirements.txt
> +git+https://github.com/openvinotoolkit/open_model_zoo.git#egg=openmodelzoo-modelapi&subdirectory=demos/common/python
That would be better indeed. I found that `-e demos/common/python` worked - but the disadvantage is that that only works from the repository root with `pip install -r demos/requirements.txt'. If someone `cd`s to the demos directory first and then does `pip install -r requirements.txt` pip fails. I will see if I can find a better general method.

2022-10-29 09:15 UTC, Wovchena commented
I opened a PR that removes a need to install ModelAPI: https://github.com/openvinotoolkit/open_model_zoo/pull/3577

2022-10-31 11:20 UTC, helena-intel commented
> I opened a PR that removes a need to install ModelAPI: https://github.com/openvinotoolkit/open_model_zoo/pull/3577

Thanks @Wovchena ! I'll close this PR.

2022-10-31 11:20 UTC, closed without merging