Documentation output image info for Segmentation Demo is misleading
openvinotoolkit/open_model_zoo pull request #3793
Opened 2023-06-16 16:25 UTC by tsavina

Ticket 110888

2023-06-16 17:00 UTC, Wovchena requested changes

2023-06-16 17:00 UTC, Wovchena commented on demos/segmentation_demo/segmentation_image.jpg
I just want to double check. Is the license of the image you used permissive enough to be redistributed/modified by Intel?

2023-06-26 14:35 UTC, tsavina commented on demos/segmentation_demo/segmentation_image.jpg
changed the image to avoid any license issues, reused the approved one from ov notebooks https://docs.openvino.ai/2022.3/notebooks/003-hello-segmentation-with-output.html

2023-06-30 06:22 UTC, Wovchena approved these changes

2023-06-30 06:23 UTC, merged